#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && mvn org.pitest:pitest-maven:mutationCoverage && cd target/site/ && python3 -m http.server
